apiVersion: v1
kind: ConfigMap
metadata:
  name: mock-server-script
data:
  mock-server.js: |
    const http = require('http');

    // This function generates a random RPS between 5,000 and 12,000
    // so you can watch your Watchdog scale up and down automatically.
    const requestListener = function (req, res) {
      const fakeRps = Math.floor(Math.random() * (12000 - 5000 + 1) + 5000);
      
      res.setHeader("Content-Type", "application/json");
      res.writeHead(200);
      res.end(JSON.stringify({ rps: fakeRps }));
      
      console.log(`Watchdog asked for metrics. Sent: ${fakeRps} RPS`);
    };

    const server = http.createServer(requestListener);
    server.listen(5000, '0.0.0.0', () => {
        console.log(`Mock Stadium API is running on port 5000`);
    });
